In [38]:
# Importa el overlay creado (La carpeta debe incluir el .bit, .hwh y .tcl con el mismo nombre)

from pynq import Overlay
import numpy as np
import pynq.lib.dma

aapvol = Overlay('/home/xilinx/pynq/overlays/aapv/aapv.bit')

dma0 = aapvol.axi_dma_0
dma1 = aapvol.axi_dma_1

In [39]:
from pynq import Xlnk
xlnk = Xlnk()

/usr/lib/python3/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: pynq.Xlnk is deprecated and will be removed in 2.7 - use pynq.allocate instead
  


In [40]:
avg = xlnk.cma_array(shape=(500,500), dtype=np.float)
cnt = xlnk.cma_array(shape=(500,500), dtype=np.int)
res = xlnk.cma_array(shape=(500,500), dtype=np.float)

for i in range(32):
    for j in range(32):
        avg[i][j] = 80;
        cnt[i][j] = 2;

In [41]:
dma0.sendchannel.transfer(avg)
dma1.sendchannel.transfer(cnt)
dma0.recvchannel.transfer(res)

ValueError: Transfer size is 2000000 bytes, which exceeds the maximum DMA buffer size 16383.

In [33]:
print(res)

[[0.3125 0.3125 0.3125 ... 0.3125 0.3125 0.3125]
 [0.3125 0.3125 0.3125 ... 0.3125 0.3125 0.3125]
 [0.3125 0.3125 0.3125 ... 0.3125 0.3125 0.3125]
 ...
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.     0.     0.    ]]
